### PR TITLE
add support for metros

### LINKED ISSUE #72: Introduce Metros as a Facility alternative
Equinix Metal facilities can now be treated as aggregate, in many ways, using metros:

https://metal.canny.io/changelog/new-metros-feature-live

1. Provide inputs that allow users to provision to a metro rather than a facility (the facility option should be preserved)
2. Expose the deployed_facility of each node in output variables

### LINKED ISSUE #82: Catalina (10.15.7) users may experience a x509 certificate signed by unknown authority when hitting api.equinix.com/metal/v1 via the provider
I found a workaround for it that worked for me here
-> https://github.com/hashicorp/terraform/issues/22193#issuecomment-610877715
The certificate whose trust I needed to set to "Use system defaults" was issued by Digicert Global Root CA and it was in fact set to "Always Trust". I needed to set it to "Use system defaults" to make it work.

### PR DESCRIPTION
**Pull request by displague**
Fixes #72 

May fix #82 

Disables ARM testing in CI due to availability constraints in previous CI runs (looking for your thoughts, @jmarhee)

### CODE REVIEW

**Comment by jmarhee** [comment]
Arm and x86 nodes use the same module to provision, so I don’t know that it matters that we test them separately unless tests on this become more comprehensive. Looks good

**Review by jmarhee — APPROVED** [review]

**Comment by displague** [comment]
CI error:

> Error: Failed to read ssh private key: no key found

I haven't had a chance to look into this. Initially thoughts are:

If the key is required, this build should provide one. The metal-project-action (GH action) can supply one.
Alternatively, this module could be modified to generate a key if not provided (maybe it already does).

If neither of those are the problem, was the path used incorrectly to lookup the key?

**Comment by jmarhee** [comment]
> CI error:
> 
> > Error: Failed to read ssh private key: no key found
> 
> I haven't had a chance to look into this. Initially thoughts are:
> 
> If the key is required, this build should provide one. The metal-project-action (GH action) can supply one.
> Alternatively, this module could be modified to generate a key if not provided (maybe it already does).
> 
> If neither of those are the problem, was the path used incorrectly to lookup the key?

The root module (this variable is only in the controller-pool submodule) should, ideally, define this, but currently does not (and does not have a default in the submodule, so it is looking for one to be supplied)-- if one can be provided by the Action, that will suffice for now, and we can address having the key-flow here match the other modules in another issue, if you don't think it would be trivial to add here.

**Comment by displague** [comment]
@jmarhee I think df3ce456f90285d8c7e8b90c6743189e6bc57cd7 will take care of this. Hoping to get a successful integration build 🤞

**Review by jmarhee — APPROVED** [review]

**Comment by displague** [comment]
Merging this for the metro improvements. 

The CI integration tests failing is not concerning because they were not getting any further before this PR (we'll investigate that in another PR).

**Pull request merged**
