### PR TITLE
Updates variables to bump Kubernetes to 1.21; Adds HOME variable to u…

### PR DESCRIPTION
**Pull request by jmarhee**
…serdata to address change in Kubeadm preflight Docker verification

Addresses #73 

Signed-off-by: Joseph D. Marhee <jmarhee@interiorae.com>

### CODE REVIEW

**Comment by jmarhee** [comment]
I bumped `kubernetes_version` to `1.21`.

I added `export HOME=/root` to the userdata for the controller and nodes in order to unblock the Docker preflight check that was preventing cluster spin-up.

**Comment by jmarhee** [comment]
In addressing the above issue, this fix deployed the cluster as anticipated (with the version bump, but also without it):

```
NAME                                      STATUS   ROLES                  AGE   VERSION
jmarhee-smartkey-lab-controller-primary   Ready    control-plane,master   32m   v1.21.0
jmarhee-smartkey-lab-x86-blue-00          Ready    <none>                 23m   v1.21.0
jmarhee-smartkey-lab-x86-blue-01          Ready    <none>                 22m   v1.21.
```

**Comment by vielmetti** [comment]
The `terraform apply` fails with

```sh
Error: The facility dc13 has no provisionable c1.large.arm servers matching your criteria

  on modules/node_pool/main.tf line 25, in resource "metal_device" "arm_node":
  25: resource "metal_device" "arm_node" {
```

There should be c1.large.arm in ewr1 for testing.

**Comment by jmarhee** [comment]
The above change to the workflow also includes bumping the `KUBERNETES_VERSION` variable to parity with `variables.tf`'s default.

**Comment by jmarhee** [comment]
Re: #76 Adding the GPU node userdata template to this PR. This is a work in progress, but the Docker driver is detected and configured, but unable to run workload, so there's more setup to be done in this script.

**Comment by jmarhee** [comment]
The most recent change configures nvidia-docker to run GPU workloads (which was a breaking issue in #76 as of the last major update to the driver configuration) -- joining the cluster should not change, but I am verifying this in a separate step.  

image

**Comment by jmarhee** [comment]
This latest change addresses the above issue with GPU pools, and should join the cluster as expected. 

image

**Comment by jmarhee** [comment]
I believe this addresses #76, so this PR should be ready for review on that issue as well:

image

**Comment by displague** [comment]
@jmarhee Looks good to me - feel free to merge. Do you want to remove the ARM count from the testing (or change facilities) to get CI to pass?

**Review by displague — APPROVED** [review]

**Pull request merged**
