### PR TITLE
initial GitHub workflow to validate Terraform configs

### PR DESCRIPTION
**Pull request by displague**
Introduces GitHub workflows:
* Check the Terraform validity (only) on pull requests and the main branch.
* Deploy the module on origin branches (and destroy all artifacts on failure or success)

The same PR was introduced for equinix/terraform-metal-vsphere#8

### CODE REVIEW

**Comment by displague** [comment]
@jmarhee This is the first module that this PR failed on 😄 

How do you feel about converting our Drone testing to an integration test in addition to the Terraform validity test that this PR adds? (separate file)

This would replace `.drone.yml`

I haven't dug into why the terraform init failed in this GitHub Workflow build, but I will need to address that in this PR.

**Comment by jmarhee** [comment]
The failing check fails on:

```
No module call named "controllers" is declared in the root module.
```

In the drone config, I declare this by copying from the `examples/` directory:

```yaml
  - cp examples/kubernetes-token.tf 00.tf
  - cp examples/kubernetes-controller-pool.tf 01.tf
  - cp examples/kubernetes-node-pool.tf 02.tf
  ```
  
  and it's referenced in `outputs.tf`:

```
  value = "\n\n Run: \n\n\t ssh root@${module.controllers.controller_addresses} kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes -w \n\n To troubleshoot (or monitor) spin-up, check the cloud-init output:\n\n\t ssh root@${module.controllers.controller_addresses} tail -f /var/log/cloud-init-output.log \n\n The initialization and spin-up process may take 5-7 minutes to complete."
  ```

so, without copying the example module (since there's no module declared, and if a user doesn't copy the example, it would not be named `controllers` necessarily), it will fail to validate because of this oversight. I recommend moving this output to the controllers example plan, not sure if we should just write up a new issue or not for this.

**Comment by jmarhee** [comment]
Also, yes, replacing the drone config with a workflow sounds fine-- the Drone config was. much more involved, and very time-consuming on each change (since it would create a non-HA and HA cluster), and I don't know if this is really necessary, so a validation check sounds fine to me.

**Review by jmarhee — APPROVED** [review]

**Comment by displague** [comment]
I added `kubeadm` to the GH worker based on the error messages, but it appears now that kubeadm is missing from the remotes and this is causing the build to fail.

I created #68 in part confusion and part hope that we can simplify this process.

**Comment by displague** [comment]
Merging this as-is. I'll open a new issue to address the failing HA test.

(The private key or ssh password is not being used. Local testing should make it easier to sort out since the devices that are provisioned won't be immediately destroyed. Because the problem is in a set of null_resource provisioners, the follow-up `terraform apply` will either work or fail immediately based on the SSH creds settings:
https://github.com/equinix/terraform-metal-multiarch-k8s/pull/67/files#diff-2e64907699df6266e0199ae63ce0e668f5dddfaa4e2d2841dc05b98efd4ac350R62-R68

**Pull request merged**
